
spring:
  application:
    name: pet-clinic
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/${PET_CLINIC_DB_NAME}
    username: ${PET_CLINIC_DB_USERNAME}
    password: ${PET_CLINIC_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.jdbc.timezone: UTC
      hibernate.hibernate.format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml